# Generated by Django 3.2.7 on 2022-01-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signUp_app', '0002_auto_20220112_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_superuser',
        ),
    ]
